In [1]:
import pandas as pd
df=pd.read_csv('dataset/student.csv')
df

        Reg_no                             Name
0   393CS22706             SUSHMA SURESH RATHOD
1   393CS22707             VIJAYAKUMAR  CHAPPAR
2   393CS22704                  KRISHNA  GEJAGE
3   393CS22705      SAHANA SHARANAGOUDA SURANUR
4   393CS22701              ABHISHEK  HATTARAKI
5   393CS21039               SUJATA RAJU JADHAV
6   393CS21013            HONMANE VIKAS BABUSHA
7   393CS21017    MAHAJANKATTI KAUSTUBH GURURAJ
8   393CS21024      PRANAV GURUBASSAYA HIREMATH
9   393CS21006                        BASAMMA
10  393CS21041        VAISHNAVI RAMANNA MALAGAR
11  393CS21007   BIRADAR VIJAYALAXMI RUDRAGOUDA
12  393CS21008      CHETAN MANIKPRABHU ANKALAGI
13  393CS21036      SOUMYA APPASAHEB ITTANGIHAL
14  393CS21034             SHAHEEN SALEEM MULLA
15  393CS21020                  NIKITA  CHAVHAN
16  393CS21022                 PRADEEP R KONNUR
17  393CS21028         SACHIN SHRISHAIL BIRADAR
18  393CS21003        AISHWARYA HANAMANT BELLAD
19  393CS21026        ROOPA APPASAHEB NIMBARAGI
20  393CS21040              SUMEETH S HANDARGAL
21  393CS21023         PRAJWAL BHEEMAPPA HARNAL
22  393CS21015                    KEERTI  DESAI
23  393CS21011     FAYAZ KHADIRPATEL CHIGAROLLI
24  393CS21005     ARATI VIJAYAKUMAR BELLUNDAGI
25  393CS21010            DILBARALISHA  MANIYAR
26  393CS21001       ABHISHEK SHANTVEER BEELAGI
27  393CS21002                    ABID  WALIKAR
28  393CS21037              SPOORTI  GHATKAMBLE
29  393CS21029     SAKSHIDEVI PRABHUGOUDA PATIL
30  393CS21042            VANSH MOHNISH AGARWAL
31  393CS21019          MOHAMMEDSUFIYAN  TORGAL
32  393CS21004                    ANJUM  TAKKOD
33  393CS21038            SPOORTI SANTOSH KURLE
34  393CS21016             LATA GANGARAM RATHOD
35  393CS21012         GIREESH NAGARAJ KABADAGI
36  393CS21030                    SANA  DALAWAI
37  393CS21032        SAVITA SHREESHAIL JUMANAL
38  393CS21035  SHIVAKUMAR MARUTEEPPA  HOSAMANI
39  393CS21014                    IRFAN  KOLHAR
40  393CS21033                  SHAHEED  KOLHAR
41  393CS21044             VIPIN NAGESH ZINGADE

In [2]:
df1=pd.read_csv('dataset/marks.csv')

In [10]:
new_df=pd.merge(df,df1,on='Reg_no')
new_df

        Reg_no                             Name  OSA  CN
0   393CS22706             SUSHMA SURESH RATHOD   44  45
1   393CS22707             VIJAYAKUMAR  CHAPPAR   97  47
2   393CS22704                  KRISHNA  GEJAGE   97  47
3   393CS22705      SAHANA SHARANAGOUDA SURANUR   97  52
4   393CS22701              ABHISHEK  HATTARAKI   75  21
5   393CS21039               SUJATA RAJU JADHAV   11  23
6   393CS21013            HONMANE VIKAS BABUSHA   87  92
7   393CS21017    MAHAJANKATTI KAUSTUBH GURURAJ   45  78
8   393CS21024      PRANAV GURUBASSAYA HIREMATH   97  17
9   393CS21006                        BASAMMA     97  47
10  393CS21041        VAISHNAVI RAMANNA MALAGAR   23  45
11  393CS21007   BIRADAR VIJAYALAXMI RUDRAGOUDA   87  65
12  393CS21008      CHETAN MANIKPRABHU ANKALAGI   61  39
13  393CS21036      SOUMYA APPASAHEB ITTANGIHAL   33  39
14  393CS21034             SHAHEEN SALEEM MULLA   53  44
15  393CS21020                  NIKITA  CHAVHAN   56  62
16  393CS21022                 PRADEEP R KONNUR   22  65
17  393CS21028         SACHIN SHRISHAIL BIRADAR   45  20
18  393CS21003        AISHWARYA HANAMANT BELLAD   25  15
19  393CS21026        ROOPA APPASAHEB NIMBARAGI   90  74
20  393CS21040              SUMEETH S HANDARGAL   31  94
21  393CS21023         PRAJWAL BHEEMAPPA HARNAL   93   3
22  393CS21015                    KEERTI  DESAI   41  89
23  393CS21011     FAYAZ KHADIRPATEL CHIGAROLLI   32  57
24  393CS21005     ARATI VIJAYAKUMAR BELLUNDAGI   90  91
25  393CS21010            DILBARALISHA  MANIYAR   76  72
26  393CS21001       ABHISHEK SHANTVEER BEELAGI   17  30
27  393CS21002                    ABID  WALIKAR   58  49
28  393CS21037              SPOORTI  GHATKAMBLE    4  24
29  393CS21029     SAKSHIDEVI PRABHUGOUDA PATIL   86  70
30  393CS21042            VANSH MOHNISH AGARWAL   24  87
31  393CS21019          MOHAMMEDSUFIYAN  TORGAL   20  11
32  393CS21004                    ANJUM  TAKKOD   37  58
33  393CS21038            SPOORTI SANTOSH KURLE   31  94
34  393CS21016             LATA GANGARAM RATHOD    7  31
35  393CS21012         GIREESH NAGARAJ KABADAGI   95  77
36  393CS21030                    SANA  DALAWAI   61  84
37  393CS21032        SAVITA SHREESHAIL JUMANAL   88  83
38  393CS21035  SHIVAKUMAR MARUTEEPPA  HOSAMANI   76  31
39  393CS21014                    IRFAN  KOLHAR    7  31
40  393CS21033                  SHAHEED  KOLHAR   77  70
41  393CS21044             VIPIN NAGESH ZINGADE   43  27

In [12]:
new_df['Total_marks']=new_df['OSA']+new_df['CN']

In [5]:
new_df

        Reg_no                             Name  OSA  CN  Total_marks
0   393CS22706             SUSHMA SURESH RATHOD   44  45           89
1   393CS22707             VIJAYAKUMAR  CHAPPAR   97  47          144
2   393CS22704                  KRISHNA  GEJAGE   97  47          144
3   393CS22705      SAHANA SHARANAGOUDA SURANUR   97  52          149
4   393CS22701              ABHISHEK  HATTARAKI   75  21           96
5   393CS21039               SUJATA RAJU JADHAV   11  23           34
6   393CS21013            HONMANE VIKAS BABUSHA   87  92          179
7   393CS21017    MAHAJANKATTI KAUSTUBH GURURAJ   45  78          123
8   393CS21024      PRANAV GURUBASSAYA HIREMATH   97  17          114
9   393CS21006                        BASAMMA     97  47          144
10  393CS21041        VAISHNAVI RAMANNA MALAGAR   23  45           68
11  393CS21007   BIRADAR VIJAYALAXMI RUDRAGOUDA   87  65          152
12  393CS21008      CHETAN MANIKPRABHU ANKALAGI   61  39          100
13  393CS21036      SOUMYA APPASAHEB ITTANGIHAL   33  39           72
14  393CS21034             SHAHEEN SALEEM MULLA   53  44           97
15  393CS21020                  NIKITA  CHAVHAN   56  62          118
16  393CS21022                 PRADEEP R KONNUR   22  65           87
17  393CS21028         SACHIN SHRISHAIL BIRADAR   45  20           65
18  393CS21003        AISHWARYA HANAMANT BELLAD   25  15           40
19  393CS21026        ROOPA APPASAHEB NIMBARAGI   90  74          164
20  393CS21040              SUMEETH S HANDARGAL   31  94          125
21  393CS21023         PRAJWAL BHEEMAPPA HARNAL   93   3           96
22  393CS21015                    KEERTI  DESAI   41  89          130
23  393CS21011     FAYAZ KHADIRPATEL CHIGAROLLI   32  57           89
24  393CS21005     ARATI VIJAYAKUMAR BELLUNDAGI   90  91          181
25  393CS21010            DILBARALISHA  MANIYAR   76  72          148
26  393CS21001       ABHISHEK SHANTVEER BEELAGI   17  30           47
27  393CS21002                    ABID  WALIKAR   58  49          107
28  393CS21037              SPOORTI  GHATKAMBLE    4  24           28
29  393CS21029     SAKSHIDEVI PRABHUGOUDA PATIL   86  70          156
30  393CS21042            VANSH MOHNISH AGARWAL   24  87          111
31  393CS21019          MOHAMMEDSUFIYAN  TORGAL   20  11           31
32  393CS21004                    ANJUM  TAKKOD   37  58           95
33  393CS21038            SPOORTI SANTOSH KURLE   31  94          125
34  393CS21016             LATA GANGARAM RATHOD    7  31           38
35  393CS21012         GIREESH NAGARAJ KABADAGI   95  77          172
36  393CS21030                    SANA  DALAWAI   61  84          145
37  393CS21032        SAVITA SHREESHAIL JUMANAL   88  83          171
38  393CS21035  SHIVAKUMAR MARUTEEPPA  HOSAMANI   76  31          107
39  393CS21014                    IRFAN  KOLHAR    7  31           38
40  393CS21033                  SHAHEED  KOLHAR   77  70          147
41  393CS21044             VIPIN NAGESH ZINGADE   43  27           70

In [13]:
new_df['Percentage']=new_df['Total_marks']/200*100

In [14]:
new_df

,Reg_no,Name,OSA,CN,Total_marks,Percentage
0,393CS22706,SUSHMA SURESH RATHOD,44,45,89,44.5
1,393CS22707,VIJAYAKUMAR CHAPPAR,97,47,144,72.0
2,393CS22704,KRISHNA GEJAGE,97,47,144,72.0
3,393CS22705,SAHANA SHARANAGOUDA SURANUR,97,52,149,74.5
4,393CS22701,ABHISHEK HATTARAKI,75,21,96,48.0
5,393CS21039,SUJATA RAJU JADHAV,11,23,34,17.0
6,393CS21013,HONMANE VIKAS BABUSHA,87,92,179,89.5
7,393CS21017,MAHAJANKATTI KAUSTUBH GURURAJ,45,78,123,61.5
8,393CS21024,PRANAV GURUBASSAYA HIREMATH,97,17,114,57.0
9,393CS21006,BASAMMA,97,47,144,72.0
10,393CS21041,VAISHNAVI RAMANNA MALAGAR,23,45,68,34.0
11,393CS21007,BIRADAR VIJAYALAXMI RUDRAGOUDA,87,65,152,76.0
12,393CS21008,CHETAN MANIKPRABHU ANKALAGI,61,39,100,50.0
13,393CS21036,SOUMYA APPASAHEB ITTANGIHAL,33,39,72,36.0
14,393CS21034,SHAHEEN SALEEM MULLA,53,44,97,48.5
15,393CS21020,NIKITA CHAVHAN,56,62,118,59.0
16,393CS21022,PRADEEP R KONNUR,22,65,87,43.5
17,393CS21028,SACHIN SHRISHAIL BIRADAR,45,20,65,32.5
18,393CS21003,AISHWARYA HANAMANT BELLAD,25,15,40,20.0
19,393CS21026,ROOPA APPASAHEB NIMBARAGI,90,74,164,82.0
20,393CS21040,SUMEETH S HANDARGAL,31,94,125,62.5
21,393CS21023,PRAJWAL BHEEMAPPA HARNAL,93,3,96,48.0
22,393CS21015,KEERTI DESAI,41,89,130,65.0
23,393CS21011,FAYAZ KHADIRPATEL CHIGAROLLI,32,57,89,44.5
24,393CS21005,ARATI VIJAYAKUMAR BELLUNDAGI,90,91,181,90.5
25,393CS21010,DILBARALISHA MANIYAR,76,72,148,74.0
26,393CS21001,ABHISHEK SHANTVEER BEELAGI,17,30,47,23.5
27,393CS21002,ABID WALIKAR,58,49,107,53.5
28,393CS21037,SPOORTI GHATKAMBLE,4,24,28,14.0
29,393CS21029,SAKSHIDEVI PRABHUGOUDA PATIL,86,70,156,78.0
30,393CS21042,VANSH MOHNISH AGARWAL,24,87,111,55.5
31,393CS21019,MOHAMMEDSUFIYAN TORGAL,20,11,31,15.5
32,393CS21004,ANJUM TAKKOD,37,58,95,47.5
33,393CS21038,SPOORTI SANTOSH KURLE,31,94,125,62.5
34,393CS21016,LATA GANGARAM RATHOD,7,31,38,19.0
35,393CS21012,GIREESH NAGARAJ KABADAGI,95,77,172,86.0
36,393CS21030,SANA DALAWAI,61,84,145,72.5
37,393CS21032,SAVITA SHREESHAIL JUMANAL,88,83,171,85.5
38,393CS21035,SHIVAKUMAR MARUTEEPPA HOSAMANI,76,31,107,53.5
39,393CS21014,IRFAN KOLHAR,7,31,38,19.0
40,393CS21033,SHAHEED KOLHAR,77,70,147,73.5
41,393CS21044,VIPIN NAGESH ZINGADE,43,27,70,35.0

In [18]:
new_df.to_csv('C:/Users/Asus/5thsem/dataset/new_stu.csv',index=False)

In [31]:
new_stu = pd.read_csv('dataset/new_stu.csv')
new_stu.head()

       Reg_no                         Name  OSA  CN  Total_marks  Percentage
0  393CS22706         SUSHMA SURESH RATHOD   44  45           89        44.5
1  393CS22707         VIJAYAKUMAR  CHAPPAR   97  47          144        72.0
2  393CS22704              KRISHNA  GEJAGE   97  47          144        72.0
3  393CS22705  SAHANA SHARANAGOUDA SURANUR   97  52          149        74.5
4  393CS22701          ABHISHEK  HATTARAKI   75  21           96        48.0

In [32]:
new_stu1 = pd.read_csv('dataset/new_stu1.csv')
new_stu1

       Reg_no    Name  OSA  CN  Total_marks  Percentage
0  393CS21001   Rahul   55  88          143        71.5
1  393CS21002  Ramesh   76  45          121        60.5
2  393CS21003   Pooja   56  67          123        61.5
3  393CS21004  shweta   80  56          136        68.0

In [35]:
df = new_stu.append(new_stu1,ignore_index=True)
df

C:\Users\Asus\AppData\Local\Temp\ipykernel_39216\3537095902.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = new_stu.append(new_stu1,ignore_index=True)

,Reg_no,Name,OSA,CN,Total_marks,Percentage
0,393CS22706,SUSHMA SURESH RATHOD,44,45,89,44.5
1,393CS22707,VIJAYAKUMAR CHAPPAR,97,47,144,72.0
2,393CS22704,KRISHNA GEJAGE,97,47,144,72.0
3,393CS22705,SAHANA SHARANAGOUDA SURANUR,97,52,149,74.5
4,393CS22701,ABHISHEK HATTARAKI,75,21,96,48.0
5,393CS21039,SUJATA RAJU JADHAV,11,23,34,17.0
6,393CS21013,HONMANE VIKAS BABUSHA,87,92,179,89.5
7,393CS21017,MAHAJANKATTI KAUSTUBH GURURAJ,45,78,123,61.5
8,393CS21024,PRANAV GURUBASSAYA HIREMATH,97,17,114,57.0
9,393CS21006,BASAMMA,97,47,144,72.0
10,393CS21041,VAISHNAVI RAMANNA MALAGAR,23,45,68,34.0
11,393CS21007,BIRADAR VIJAYALAXMI RUDRAGOUDA,87,65,152,76.0
12,393CS21008,CHETAN MANIKPRABHU ANKALAGI,61,39,100,50.0
13,393CS21036,SOUMYA APPASAHEB ITTANGIHAL,33,39,72,36.0
14,393CS21034,SHAHEEN SALEEM MULLA,53,44,97,48.5
15,393CS21020,NIKITA CHAVHAN,56,62,118,59.0
16,393CS21022,PRADEEP R KONNUR,22,65,87,43.5
17,393CS21028,SACHIN SHRISHAIL BIRADAR,45,20,65,32.5
18,393CS21003,AISHWARYA HANAMANT BELLAD,25,15,40,20.0
19,393CS21026,ROOPA APPASAHEB NIMBARAGI,90,74,164,82.0
20,393CS21040,SUMEETH S HANDARGAL,31,94,125,62.5
21,393CS21023,PRAJWAL BHEEMAPPA HARNAL,93,3,96,48.0
22,393CS21015,KEERTI DESAI,41,89,130,65.0
23,393CS21011,FAYAZ KHADIRPATEL CHIGAROLLI,32,57,89,44.5
24,393CS21005,ARATI VIJAYAKUMAR BELLUNDAGI,90,91,181,90.5
25,393CS21010,DILBARALISHA MANIYAR,76,72,148,74.0
26,393CS21001,ABHISHEK SHANTVEER BEELAGI,17,30,47,23.5
27,393CS21002,ABID WALIKAR,58,49,107,53.5
28,393CS21037,SPOORTI GHATKAMBLE,4,24,28,14.0
29,393CS21029,SAKSHIDEVI PRABHUGOUDA PATIL,86,70,156,78.0
30,393CS21042,VANSH MOHNISH AGARWAL,24,87,111,55.5
31,393CS21019,MOHAMMEDSUFIYAN TORGAL,20,11,31,15.5
32,393CS21004,ANJUM TAKKOD,37,58,95,47.5
33,393CS21038,SPOORTI SANTOSH KURLE,31,94,125,62.5
34,393CS21016,LATA GANGARAM RATHOD,7,31,38,19.0
35,393CS21012,GIREESH NAGARAJ KABADAGI,95,77,172,86.0
36,393CS21030,SANA DALAWAI,61,84,145,72.5
37,393CS21032,SAVITA SHREESHAIL JUMANAL,88,83,171,85.5
38,393CS21035,SHIVAKUMAR MARUTEEPPA HOSAMANI,76,31,107,53.5
39,393CS21014,IRFAN KOLHAR,7,31,38,19.0
40,393CS21033,SHAHEED KOLHAR,77,70,147,73.5
41,393CS21044,VIPIN NAGESH ZINGADE,43,27,70,35.0
42,393CS21001,Rahul,55,88,143,71.5
43,393CS21002,Ramesh,76,45,121,60.5
44,393CS21003,Pooja,56,67,123,61.5
45,393CS21004,shweta,80,56,136,68.0

In [36]:
df1=pd.concat([new_stu,new_stu1],ignore_index=True)
df1

,Reg_no,Name,OSA,CN,Total_marks,Percentage
0,393CS22706,SUSHMA SURESH RATHOD,44,45,89,44.5
1,393CS22707,VIJAYAKUMAR CHAPPAR,97,47,144,72.0
2,393CS22704,KRISHNA GEJAGE,97,47,144,72.0
3,393CS22705,SAHANA SHARANAGOUDA SURANUR,97,52,149,74.5
4,393CS22701,ABHISHEK HATTARAKI,75,21,96,48.0
5,393CS21039,SUJATA RAJU JADHAV,11,23,34,17.0
6,393CS21013,HONMANE VIKAS BABUSHA,87,92,179,89.5
7,393CS21017,MAHAJANKATTI KAUSTUBH GURURAJ,45,78,123,61.5
8,393CS21024,PRANAV GURUBASSAYA HIREMATH,97,17,114,57.0
9,393CS21006,BASAMMA,97,47,144,72.0
10,393CS21041,VAISHNAVI RAMANNA MALAGAR,23,45,68,34.0
11,393CS21007,BIRADAR VIJAYALAXMI RUDRAGOUDA,87,65,152,76.0
12,393CS21008,CHETAN MANIKPRABHU ANKALAGI,61,39,100,50.0
13,393CS21036,SOUMYA APPASAHEB ITTANGIHAL,33,39,72,36.0
14,393CS21034,SHAHEEN SALEEM MULLA,53,44,97,48.5
15,393CS21020,NIKITA CHAVHAN,56,62,118,59.0
16,393CS21022,PRADEEP R KONNUR,22,65,87,43.5
17,393CS21028,SACHIN SHRISHAIL BIRADAR,45,20,65,32.5
18,393CS21003,AISHWARYA HANAMANT BELLAD,25,15,40,20.0
19,393CS21026,ROOPA APPASAHEB NIMBARAGI,90,74,164,82.0
20,393CS21040,SUMEETH S HANDARGAL,31,94,125,62.5
21,393CS21023,PRAJWAL BHEEMAPPA HARNAL,93,3,96,48.0
22,393CS21015,KEERTI DESAI,41,89,130,65.0
23,393CS21011,FAYAZ KHADIRPATEL CHIGAROLLI,32,57,89,44.5
24,393CS21005,ARATI VIJAYAKUMAR BELLUNDAGI,90,91,181,90.5
25,393CS21010,DILBARALISHA MANIYAR,76,72,148,74.0
26,393CS21001,ABHISHEK SHANTVEER BEELAGI,17,30,47,23.5
27,393CS21002,ABID WALIKAR,58,49,107,53.5
28,393CS21037,SPOORTI GHATKAMBLE,4,24,28,14.0
29,393CS21029,SAKSHIDEVI PRABHUGOUDA PATIL,86,70,156,78.0
30,393CS21042,VANSH MOHNISH AGARWAL,24,87,111,55.5
31,393CS21019,MOHAMMEDSUFIYAN TORGAL,20,11,31,15.5
32,393CS21004,ANJUM TAKKOD,37,58,95,47.5
33,393CS21038,SPOORTI SANTOSH KURLE,31,94,125,62.5
34,393CS21016,LATA GANGARAM RATHOD,7,31,38,19.0
35,393CS21012,GIREESH NAGARAJ KABADAGI,95,77,172,86.0
36,393CS21030,SANA DALAWAI,61,84,145,72.5
37,393CS21032,SAVITA SHREESHAIL JUMANAL,88,83,171,85.5
38,393CS21035,SHIVAKUMAR MARUTEEPPA HOSAMANI,76,31,107,53.5
39,393CS21014,IRFAN KOLHAR,7,31,38,19.0
40,393CS21033,SHAHEED KOLHAR,77,70,147,73.5
41,393CS21044,VIPIN NAGESH ZINGADE,43,27,70,35.0
42,393CS21001,Rahul,55,88,143,71.5
43,393CS21002,Ramesh,76,45,121,60.5
44,393CS21003,Pooja,56,67,123,61.5
45,393CS21004,shweta,80,56,136,68.0